org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Sürümleri 1.21.4 için kilitliyoruz
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.2
loader_version=0.16.10

# Mod Ayarları
mod_version=1.0.0
mod_group=net.storm.optimizer
mod_id=storm_crystal_optimizer